name: ed25519_hd_key
version: 2.2.1

description: BIP-0032 like derivation for ed25519 curve
repository: https://github.com/alepop/dart-ed25519-hd-key

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.3
  pinenacl: ^0.5.1

dev_dependencies:
  test: ^1.16.8
  convert: ^3.0.0
