name: ed25519_hd_key
version: 1.0.1

description: BIP-0032 like derivation for ed25519 curve
author: Aleksey Popov <alepooop@gmail.com>
homepage: https://github.com/alepop/dart-ed25519-hd-key

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  tweetnacl: ^0.3.1
  pointycastle: ^1.0.0
  hex: ^0.1.2

dev_dependencies:
  test: ^1.0.0